@ECHO OFF

set ANTLR4_VERSION=4.0-SNAPSHOT
set ANTLR3_VERSION=3.4.1-SNAPSHOT
set ST4_VERSION=4.0.4-SNAPSHOT

set ANTLR_MAVEN_HOME=%USERPROFILE%\.m2\repository\org\antlr

set ANTLR3_RUNTIME_JAR=%ANTLR_MAVEN_HOME%\antlr-runtime\%ANTLR3_VERSION%\antlr-runtime-%ANTLR3_VERSION%.jar
set ANTLR3_RUNTIME_CLASSPATH=%ANTLR3_RUNTIME_JAR%
set ANTLR4_RUNTIME_JAR=%ANTLR_MAVEN_HOME%\antlr4-runtime\%ANTLR4_VERSION%\antlr4-runtime-%ANTLR4_VERSION%.jar
set ANTLR4_RUNTIME_CLASSPATH=%ANTLR4_RUNTIME_JAR%

set ST4_CLASSPATH=%ANTLR_MAVEN_HOME%\ST4\%ST4_VERSION%\ST4-%ST4_VERSION%.jar;%ANTLR3_RUNTIME_CLASSPATH%

set ANTLR3_TOOL_JAR=%ANTLR_MAVEN_HOME%\antlr\%ANTLR3_VERSION%\antlr-%ANTLR3_VERSION%.jar
set ANTLR3_CLASSPATH=%ANTLR3_TOOL_JAR%;%ST4_CLASSPATH%
set ANTLR4_TOOL_JAR=%ANTLR_MAVEN_HOME%\antlr4\%ANTLR4_VERSION%\antlr4-%ANTLR4_VERSION%.jar
set ANTLR4_CLASSPATH=%ANTLR4_TOOL_JAR%;%ST4_CLASSPATH%;%ANTLR4_RUNTIME_CLASSPATH%

set ANTLR3_TOOL=-cp %ANTLR3_CLASSPATH% org.antlr.Tool
set ANTLR4_TOOL=-cp %ANTLR4_CLASSPATH% org.antlr.v4.Tool

set SOURCE_ROOT=%CD%

set ANTLR3_RUNTIME_WRAPPER_DIR=org-antlr-runtime\release\modules\ext
set ANTLR3_TOOL_WRAPPER_DIR=org-antlr\release\modules\ext
set ANTLR4_RUNTIME_WRAPPER_DIR=org-antlr-v4-runtime\release\modules\ext
set ANTLR4_TOOL_WRAPPER_DIR=org-antlr-v4\release\modules\ext

copy %ANTLR3_RUNTIME_JAR% %ANTLR3_RUNTIME_WRAPPER_DIR%
copy %ANTLR3_TOOL_JAR% %ANTLR3_TOOL_WRAPPER_DIR%
